### ISSUE TITLE
Update button color in verify email

### ISSUE THREAD

**Issue by kimbalinski** [FRCTeam238/MyTeam238#1]
Is it possible to update the buttons to reflect brand standards?

**Comment by alexherreid** [comment]
Could you be more specific? Do you mean the frame of the email is missing something, or simply that the confirm button should be a different color?
Generally speaking- bootstrap (which we work in) uses green for "success", yellow for "warning", red for "danger" and blue/gray for "default" buttons. We don't have to follow that, but generally that is how they're positioned right now.
