### ISSUE TITLE
Error when attempting to sign the Behavior Contract

### ISSUE THREAD

**Issue by TQuag** [FRCTeam238/MyTeam238#10]
when asked to legally sign the behavior contract, ERROR 1025 persists.

**Comment by alexherreid** [comment]
Hey,
I've checked the database on this one. It looks like your "legal first name" that was entered was "Trevorq". I'm assuming it was just a fat-fingered key when setting up the account. As such, each time you would try to sign as "Trevor" it would think it wasn't the right legal name. 

I'm going to close this one, as  no fix needed, but I'm going to make sure it lists the legal name somewhere in the account (which would have helped us see this). Thanks
