### ISSUE TITLE
When changing profile picture, Bad Request occurs

### ISSUE THREAD

**Issue by TQuag** [FRCTeam238/MyTeam238#11]
when "Change Profile Picture" button is pressed after file is uploaded site claims "Your browser sent a request that this server could not understand."

**Comment by alexherreid** [comment]
Trevor, can you re-try this? I've made adjustments

**Comment by TQuag** [comment]
After successfully uploading an image as my profile picture i can say bad request no longer appears. I'm going to close the issue.
