### ISSUE TITLE
Emergency Contact

### ISSUE THREAD

**Issue by kimbalinski** [FRCTeam238/MyTeam238#3]
A little odd that they have to search for someone before being able to see the fields to add the name - anyway to show both?

**Comment by alexherreid** [comment]
We may need to discuss this one further. Let me clarify why it works this way, for example. 
Under the hood, when adding an emer contact manually, it's creating a "shadow" account that's used only as the emergency contact. The preferred use (and one that potentially is more likely) is that the person's emergency contact already has an account, and we just need them to link them. Therefore, I have them search first, in case the user doesn't know their contact already has an account, and if they really don't, then we show how to add them.
We can review on Tuesday, and evaluate a change.

**Comment by Tommy238** [comment]
I think it might not always be the case that a student's emergency contact is a parent. It could be a grandparent that is more available during the daytime or something like that.

**Comment by Tommy238** [comment]
Also, as a mentor it is highly unlikely that my emergency contact is going to have a team account.
