### ISSUE TITLE
Invited Someone to Join: Error when verifying their email

### ISSUE THREAD

**Issue by kimbalinski** [FRCTeam238/MyTeam238#5]
Warning: Missing argument 4 for Data::doCreateAccount(), called in /home/frcorg/STAGING-MY/includes/data.class.php on line 246 and defined in /home/frcorg/STAGING-MY/includes/data.class.php on line 53
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1

**Comment by alexherreid** [comment]
resolved
