### ISSUE TITLE
Date of Birth/At least 13 years old feature

### ISSUE THREAD

**Issue by kimbalinski** [FRCTeam238/MyTeam238#6]
I think we'll run into problems asking parents for date of birth as it is not relevant to their relationship with the team. Possible to keep the checkbox and move the DOB to elsewhere on the profile? Would be nice to have for students and mentors so we can do monthly birthday celebrations or something

**Comment by alexherreid** [comment]
This may be one we need to discuss in person.
The DOB/age verification is very much embedded in the account activation. The main reason for this is the account safety- making sure we aren't collecting information on minors (which we can't legally have in our database). 
I would also be interested in knowing if others think people would have resistance to entering their DOB. I can understand not wanting it to be displayed somewhere- which is fine, we can make sure it isn't displayed anywhere. 
I'll tag this for discussion.

**Comment by Tommy238** [comment]
I think if we attach a note under the DOB line stating:  "For age verification only, will not be displayed to public" that may be good to avoid people not wanting to enter it.

**Comment by alexherreid** [comment]
OK- I'm going to do a hybrid of these for now. @KPJ238 I'm sensitive to your idea that people may be turned off without a clear reasoning to the info, but it's also a useful piece of info about a student, in an emergency context. Anyway, I've added clarification to the page and am open to additional feedback on it. It now explains what it's for, no more checkbox.
