### ISSUE TITLE
Behavior Contract Screen

### ISSUE THREAD

**Issue by kimbalinski** [FRCTeam238/MyTeam238#7]
It's prefilling my email address into the Legal Last Name and leaving Legal First Name black - not sure if some settings need to be adjusted there

**Comment by alexherreid** [comment]
I have checked, and there is no code to prefill any fields on that page. I suspect what you're seeing is your browser- just like when browsers can prefill your credit card or content within pages.
I'm going to mark this as resolved for now, but if it happens on a computer that doesn't know you (like a private browser window, public machine, etc) or someone else sees this behavior, please re-open.
Thanks
